[workspace]
members = ["yarsge-core", "yarsge-sdl2"]
resolver = "3"

[workspace.package]
authors = ["Skyler Ross <orangesnowfox@gmail.com>"]
edition = "2024"
version = "0.1.0"


[workspace.dependencies.yarsge-core]
path = "yarsge-core"

[profile.dev.package.yarsge-core]
opt-level = 1
