[package]
authors.workspace = true
edition.workspace = true
name = "yarsge-sdl2"
version.workspace = true

[dependencies]
anyhow = "1.0.28"
env_logger = "0.9.0"
log = "0.4.14"
rgb = "0.8.52"
sdl2 = "0.38.0"
yarsge-core.workspace = true

[dependencies.clap]
features = ["derive"]
version = "4.0.0"
